spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/learning_management?createDatabaseIfNotExist=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:123456789}

  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform

  web:
    resources:
      add-mappings: false

app:
  jwtSecret: ${JWT_SECRET:mySecretKey1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ}
  jwtExpirationMs: ${JWT_EXPIRATION:604800000}
  default-admin:
    username: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:admin123}
    email: ${ADMIN_EMAIL:admin@gmail.com}

logging:
  level:
    "[com.lms.dev]": ${APP_LOG_LEVEL:DEBUG}
    "[org.springframework.security]": ${SECURITY_LOG_LEVEL:DEBUG}